# Generated by Django 5.2 on 2025-05-09 16:41

import achievements.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_remove_achievement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-points_reward', 'title']},
        ),
        migrations.AddField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(upload_to='achievements/icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), achievements.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='requirements',
            field=models.JSONField(help_text='Criteria to unlock achievement', validators=[achievements.models.validate_achievement_requirements]),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['type', 'is_active'], name='achievement_type_a46172_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['points_reward'], name='achievement_points__625084_idx'),
        ),
    ]
