# Generated by Django 5.2 on 2025-05-12 10:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# courses.migrations.0008_lesson_unique_constraint
# courses.migrations.0015_update_existing_courses

def fix_lesson_numbers(apps, schema_editor):
    """
    Ensure lesson numbers are unique within each course.
    This function was originally in courses.migrations.0008_lesson_unique_constraint
    """
    Lesson = apps.get_model('courses', 'Lesson')
    Course = apps.get_model('courses', 'Course')
    
    for course in Course.objects.all():
        lessons = Lesson.objects.filter(course=course).order_by('id')
        for index, lesson in enumerate(lessons, start=1):
            if lesson.number != index:
                lesson.number = index
                lesson.save()

def update_existing_courses(apps, schema_editor):
    """
    Update existing courses with proper values.
    This function was originally in courses.migrations.0015_update_existing_courses
    """
    Course = apps.get_model('courses', 'Course')
    
    # Update all courses to ensure they have proper values
    for course in Course.objects.all():
        # Set default category if empty
        if not course.category:
            course.category = 'General'
        
        # Ensure points is set (copy from points_reward if needed)
        if hasattr(course, 'points_reward') and (not course.points or course.points == 0):
            course.points = getattr(course, 'points_reward', 0)
        
        course.save()

class Migration(migrations.Migration):

    replaces = [('courses', '0001_initial'), ('courses', '0002_initial'), ('courses', '0003_remove_pathcourse_path_remove_pathcourse_course_and_more'), ('courses', '0004_remove_lesson_points_reward_course_points_reward'), ('courses', '0005_unlockedlesson_completed_at'), ('courses', '0006_remove_course_estimated_duration_course_duration_and_more'), ('courses', '0007_alter_lesson_options_lesson_duration_lesson_number_and_more'), ('courses', '0008_lesson_unique_constraint'), ('courses', '0009_lesson_unique_constraint'), ('courses', '0010_courseenrollment'), ('courses', '0011_alter_courseprogress_unique_together_and_more'), ('courses', '0012_alter_usercourseprogress_options_and_more'), ('courses', '0013_course_points_required'), ('courses', '0014_course_image_alter_unlockedcourse_unlocked_at'), ('courses', 'fix_usercourseprogress_fk'), ('courses', 'fix_points_column'), ('courses', '0014_rename_points_reward_to_points'), ('courses', '0015_update_existing_courses'), ('courses', '0016_merge_20250512_1128'), ('courses', '0017_merge_0016_merge_20250512_1128_fix_points_column')]

    dependencies = [
        ('quizzes', '0001_initial'),
        ('users', '0001_initial'),
        ('users', '0017_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('course_type', models.CharField(choices=[('SOFT', 'Soft Skills'), ('HARD', 'Hard Skills')], max_length=4)),
                ('points_required', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20)),
                ('prerequisites', models.ManyToManyField(blank=True, to='courses.course')),
                ('points_reward', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0, help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('points_required', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
                ('duration', models.IntegerField(default=0, help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('number', models.IntegerField(default=1, help_text='Lesson number/order within the course')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('completed_quizzes', models.ManyToManyField(to='quizzes.quiz')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('completed_lessons', models.ManyToManyField(to='courses.lesson')),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='UnlockedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('points_spent', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='UnlockedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.RunPython(
            code=fix_lesson_numbers,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='unlockedcourse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='unlockedcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='unlockedcourse',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='unlockedlesson',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='unlockedlesson',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='unlockedlesson',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='points_required',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='points_required',
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='course',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('SOFT', 'Soft Skill'), ('HARD', 'Hard Skill')], max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=15),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(max_length=500),
        ),
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_lessons', models.ManyToManyField(related_name='completed_by', to='courses.lesson')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_progress', to='users.profile')),
            ],
            options={
                'unique_together': {('user', 'course')},
                'verbose_name': 'User Course Progress',
                'verbose_name_plural': 'User Course Progress',
            },
        ),
        migrations.DeleteModel(
            name='CourseProgress',
        ),
        migrations.DeleteModel(
            name='UnlockedCourse',
        ),
        migrations.DeleteModel(
            name='UnlockedLesson',
        ),
        migrations.CreateModel(
            name='UnlockedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_lessons', to='users.profile')),
            ],
            options={
                'verbose_name': 'Unlocked Lesson',
                'verbose_name_plural': 'Unlocked Lessons',
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='points_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/'),
        ),
        migrations.CreateModel(
            name='UnlockedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_courses', to='users.profile')),
            ],
            options={
                'verbose_name': 'Unlocked Course',
                'verbose_name_plural': 'Unlocked Courses',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.RunSQL(
            sql='\n            ALTER TABLE courses_usercourseprogress \n            DROP CONSTRAINT courses_usercourseprogress_user_id_16683a45_fk_auth_user_id;\n            \n            ALTER TABLE courses_usercourseprogress\n            ADD CONSTRAINT courses_usercourseprogress_user_id_fk_users_profile\n            FOREIGN KEY (user_id) REFERENCES users_profile(id)\n            ON DELETE CASCADE;\n            ',
            reverse_sql='\n            ALTER TABLE courses_usercourseprogress \n            DROP CONSTRAINT courses_usercourseprogress_user_id_fk_users_profile;\n            \n            ALTER TABLE courses_usercourseprogress\n            ADD CONSTRAINT courses_usercourseprogress_user_id_16683a45_fk_auth_user_id\n            FOREIGN KEY (user_id) REFERENCES auth_user(id)\n            ON DELETE CASCADE;\n            ',
        ),
        migrations.RunSQL(
            sql='\n            -- First, update points with points_reward values where points is 0 or NULL\n            UPDATE courses_course \n            SET points = points_reward \n            WHERE (points IS NULL OR points = 0) AND points_reward > 0;\n            \n            -- Then drop the points_reward column\n            ALTER TABLE courses_course DROP COLUMN points_reward;\n            ',
            reverse_sql='\n            ALTER TABLE courses_course ADD COLUMN points_reward integer;\n            UPDATE courses_course SET points_reward = points;\n            ',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='points_reward',
            new_name='points',
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(default='0.00', max_length=20),
        ),
        migrations.RunPython(
            code=update_existing_courses,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
