# Generated by Django 5.1.6 on 2025-04-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathcourse',
            name='path',
        ),
        migrations.RemoveField(
            model_name='pathcourse',
            name='course',
        ),
        migrations.DeleteModel(
            name='LearningPath',
        ),
        migrations.DeleteModel(
            name='PathCourse',
        ),
    ]
