# Generated by Django 5.1.6 on 2025-03-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_unlockedlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='points_required',
            field=models.IntegerField(default=0),
        ),
    ]
