# Generated by Django 5.2 on 2025-04-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_pathcourse_path_remove_pathcourse_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='points_reward',
        ),
        migrations.AddField(
            model_name='course',
            name='points_reward',
            field=models.IntegerField(default=0),
        ),
    ]
