# Generated by Django 5.2 on 2025-04-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_lesson_points_reward_course_points_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlockedlesson',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
