# Generated by Django 5.2 on 2025-04-14 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_unlockedlesson_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='estimated_duration',
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/'),
        ),
    ]
