# Generated by Django 5.2 on 2025-04-14 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lesson_unique_constraint'),
    ]

    operations = [
    ]
