# Generated by Django 5.2 on 2025-05-11 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_courseprogress_unique_together_and_more'),
        ('users', '0017_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourseprogress',
            options={'verbose_name': 'User Course Progress', 'verbose_name_plural': 'User Course Progress'},
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_progress', to='users.profile'),
        ),
        migrations.CreateModel(
            name='UnlockedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_courses', to='users.profile')),
            ],
            options={
                'verbose_name': 'Unlocked Course',
                'verbose_name_plural': 'Unlocked Courses',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='UnlockedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_lessons', to='users.profile')),
            ],
            options={
                'verbose_name': 'Unlocked Lesson',
                'verbose_name_plural': 'Unlocked Lessons',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
