# Generated by Django 5.2 on 2025-05-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_usercourseprogress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='points_required',
            field=models.IntegerField(default=0),
        ),
    ]
