# Generated by Django 5.2 on 2025-05-11 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_points_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/'),
        ),
        migrations.AlterField(
            model_name='unlockedcourse',
            name='unlocked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
