# Generated by Django 5.2 on 2025-05-20 10:00

from django.db import migrations, models
from django.core.validators import MinValueValidator, MaxValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_points_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='points_reward',
            new_name='points',
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0.0, validators=[MinValueValidator(0.0), MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(default='0.00', max_length=20),
        ),
    ]
