# Generated by Django 5.2 on 2025-05-20 10:15

from django.db import migrations

def update_existing_courses(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    
    # Update all existing courses
    for course in Course.objects.all():
        # Convert price to string
        if isinstance(course.price, (int, float)):
            course.price = str(course.price)
            
        course.save()

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_rename_points_reward_to_points'),
    ]

    operations = [
        migrations.RunPython(update_existing_courses),
    ]
