# Generated by Django 5.2 on 2025-05-12 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_update_existing_courses'),
        ('courses', 'fix_usercourseprogress_fk'),
    ]

    operations = [
    ]
