# Generated by Django 5.2 on 2025-05-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_merge_20250512_1128'),
        ('courses', 'fix_points_column'),
    ]

    operations = [
    ]
