# Generated by Django 5.1.6 on 2025-04-09 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='users_profi_user_id_783607_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='users_profi_points_da4051_idx',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_active',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='account_deactivated',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='deactivation_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='device_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notification_preferences',
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
