# Generated by Django 5.2 on 2025-04-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verification_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='code_created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
