# Generated by Django 5.2 on 2025-05-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_squashed_migrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ROOKIE', 'Rookie'), ('EXPLORER', 'Explorer'), ('ACHIEVER', 'Achiever'), ('MASTER', 'Master'), ('GRANDMASTER', 'Grandmaster')], max_length=20)),
                ('min_points', models.IntegerField()),
                ('max_points', models.IntegerField()),
                ('badge_url', models.URLField(blank=True)),
            ],
        ),
    ]
